# knife4j增强配置
knife4j:
  # 是否开启生产环境保护策略
  production: true

# 数据库连接配置
spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    # druid数据库连接池
    # type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.2.101:3306/darius_pre?characterEncoding=utf8&serverTimezone=Asia/Shanghai
    username: darius_pre
    password: darius_pre_krN4Dw
    hikari:
      # 客户端从连接池等待连接的最大毫秒数
      connection-timeout: 20000
      # 连接池中维护的最小空闲连接数
      minimum-idle: 5
      # 最大连接池数大小
      maximum-pool-size: 20
      # 允许一个连接在连接池中闲置的最大毫秒数
      idle-timeout: 300000
      # 池中连接关闭后的最长生存毫秒数
      max-lifetime: 1200000
      # 从池中返回的连接的默认自动提交行为
      auto-commit: true

# 线程池配置
thread:
  pool:
    # 设置核心线程数
    core-pool-size: 5
    # 设置最大线程数
    max-pool-size: 20
    # 设置缓冲队列大小
    queue-capacity: 100
    # 设置线程的最大空闲秒数
    keep-alive-seconds: 30
    # 是否允许核心线程超时
    allow-core-thread-timeout: true
    # 是否等待剩余任务完成后才关闭应用
    wait-for-tasks-to-complete-on-shutdown: true
    # 等待剩余任务完成的最大秒数
    await-termination-seconds: 60
    # 拒绝策略
    rejected-execution-handler: CallerRunsPolicy

# p6spy配置
decorator:
  datasource:
    enabled: false

# 项目配置
darius:
  # 验证码
  captcha:
    enabled: true
    # 验证码类型
    type: image
    # 图形验证码类型，验证码类型为图形时需配置
    image-type: arithmetic